### ISSUE TITLE
odl-cpp-utils doesn't build after Eigen removal

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odlpp#7]
You removed Eigen in
https://github.com/odlgroup/odlpp/commit/9196001425a958bb25f8a11657515a8fe79d8de4

But it is still referenced in
https://github.com/odlgroup/odl-cpp-utils/blob/master/utils/Ellipse.h

So Jenkins CI can't build the project from scratch, it gets Cannot open include file: 'Eigen/Core' No such file or directory.

Revert the Eigen deletion, or update odl-cpp-utils?

/Lars

**Comment by adler-j** [comment]
This only happens if you try to `make`, which tries to make all subprojects, including the ones requiring Eigen. If you instead `make pyinstall`, it only makes the ones that you need, and those don't require Eigen.

Correct me if I'm wrong here.

One option could be to somehow try to exclude these projects, possibly by a `HAS_EIGEN` flag in `odl-cpp-utils`.

**Comment by LarsWestergren** [comment]
That is correct, mistake in Jenkins config so I built the default target. Suggest closing issue.
